### ISSUE TITLE
Additional loader required due to usage of ??/?. operators

### ISSUE THREAD

**Issue by pvillaverde** [felixfbecker/dom-to-svg#88]
Hey there!

I've just found this library but can't test it on a new angular app because of the ES2020. I've tried some workarrounds but no sucess, how can I specify it on the compiler options so typescript understands it?
```
] Error: ./node_modules/dom-to-svg/lib/index.js 34:34
[ng] Module parse failed: Unexpected token (34:34)
[ng] File was processed with these loaders:
[ng]  * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
[ng]  * ./node_modules/@ngtools/webpack/src/ivy/index.js
[ng] You may need an additional loader to handle the result of these loaders.
[ng] |         }
[ng] |         // Make font URLs absolute (need to be resolved relative to the stylesheet)
[ng] >         for (const rule of rules ?? []) {
[ng] |             if (!css_1.isCSSFontFaceRule(rule)) {
[ng] |                 continue;
```

**Comment by felixfbecker** [comment]
This operator has been supported in all modern browsers for over a year, with the unsupported versions having barely any usage left: https://caniuse.com/mdn-javascript_operators_nullish_coalescing

I'm not familiar with Angular, but looks like using Babel as a Webpack loader would fix it?

**Comment by pvillaverde** [comment]
> This operator has been supported in all modern browsers for over a year, with the unsupported versions having barely any usage left: https://caniuse.com/mdn-javascript_operators_nullish_coalescing
> 
> I'm not familiar with Angular, but looks like using Babel as a Webpack loader would fix it?

Indeed modern browsers do support it, but for mobile is different, many people still use 2-7 year old phones and we need to keep it compatible for now, so we can't use modern features, at least on the compiled version :(

I'm already using babel loader but haven't figured it out what's the problem yet. Thanks for the answer anyway!

**Comment by shok333** [comment]
Hello, we met with this problem, when we imported the lib to our next.js project. The problem was with "??" and "?." operators. We've fixed the problem, when we transpiled files with the operators using online babel transpiler.

**Comment by shok333** [comment]
@felixfbecker, I suggest to get rid of these operators.

**Comment by felixfbecker** [comment]
This would make the code more complex and harder to read in many places (and the code is already inherently complex to begin with). I would suggest using Babel in your bundler config. You may need to configure it properly so that it doesn't exclude everything inside `node_modules`, but also considers this library. I can't unfortunately give more advice without knowing which bundler you use, what your config is etc.

**Comment by pjose16** [comment]
@pvillaverde Hello, I am facing the same issue, could you resolve the issue?

**Comment by pvillaverde** [comment]
> @pvillaverde Hello, I am facing the same issue, could you resolve the issue?

Hey there, I ended up using this library https://github.com/tsayen/dom-to-image with a small modification in order to include shadow root too.

**Comment by lucaslar** [comment]
### Suggested solution (?)

Hello there, I faced the same problem in an Angular (11) application. The operators themselves should not be the problem since they can be used in Angular, too. It rather seems to be the package's `target` being `ES2020`. 

You should be able to keep using the operators with `module: ES2020` but can still target an older JavaScript version &rarr; TypeScript will then be compiled regarding the targeted version, i.e. the operators are converted ([see here](https://stackoverflow.com/a/42429053/8228988)). As an interim solution, I cloned your repository, changed the `target` in `tsconfig.json` to `es2018`, packed it and installed this local version in my application. Obviously, it's not a real solution in the long run, but **it works!**

@felixfbecker Is there a specific reason you set the `target` to `ES2020` instead of an older version? If not, would you consider releasing a version with an updated `target` (I'm not talking about CommonJS as proposed in #2 or any other version that requires code changes)?. The Angular-world (or rather the "< `ES2020` world") would be a better place if it could use that package. It works like a charm!

---

### Another thought (unsuccessful)

Also, I've tried to set both the `lib` and `target` of my Angular application to `ES2020` but that did not work. I assume it has to do with loaders, but perhaps someone else reading this knows more and would like to explain it - I'd be happy to learn! As a matter of fact, the default `lib` (`es2018`), `target` (`es2015`) and `module` (`es2020`) versions of the Angular application are different, too, which I think is a good approach in order to support older browsers as @pvillaverde mentioned. Thus, these versions should preferably not be changed in my opinion.

**Comment by lucaslar** [comment]
Hello again, I forked the repository and created a pull request. 

For Angular/<`ES2020` users: In this forked repository, I also added a branch `feature/npm-prepare` with a `prepare` script in `package.json` which builds the project. This allows to install the package (targeting `ES2018`) from GitHub directly by running:
```shell
npm install git+https://github.com/lucaslar/dom-to-svg.git#feature/npm-prepare
```
Of course, as soon as this issue is closed, this solution is not necessary any longer.

**Comment by MartinGerritsen** [comment]
@lucaslar Could you merge your changes with the latest changes? Or maybe we could merge your changes, @felixfbecker ?
I'm also working in Angular and Lucas's version worked like a charm, but it doesn't have the latest changes :) 

Thanks!

**Comment by felixfbecker** [comment]
Alright, since this seems to be in very high demand (more than I would have thought), I changed the target to ES2019, which transpiles `?.` and `??`. Hope this works for you all and thanks for the thoughtful comments!

**Comment by lucaslar** [comment]
Thanks a lot, it works perfectly!
